cp:
  fhir-server-uri:
  open-fhir-server-uri:

spring:
  security:
    oauth2:
      client:
        registration:
          cp-client:
            client-id:
            client-secret:
            client-name: Gravity-SDOH-CP-App
            provider: cp-provider
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            # scope 'launch/patient' for a standalone launch if needed.
            # user/*.* will give us full access to resources in Logica sendbox (might be a bug), should be system/*.*
            scope: 'user/*.*,fhirUser,openid,launch'
        provider:
          cp-provider:
            token-uri: https://auth.logicahealth.org/token
            # We need to explicitly set the 'aud' query param to enable standalone launch.
            authorization-uri: https://auth.logicahealth.org/authorize?aud=${cp.fhir-server-uri}
            user-info-uri: https://auth.logicahealth.org/userinfo
            jwk-set-uri: https://auth.logicahealth.org/jwk
            userNameAttribute: sub

swagger:
  title: SDOH Exchange CP App API
  contact:
    name: Gravity Project
    url: https://www.hl7.org/gravity/
scheduling:
  task-polling-delay-millis: 10000
